import type { Locale } from "@/i18n/config";
import type { DemoFormCopy } from "./DemoRequestForm";

// Single source of truth for the demo-request dialog copy across the three
// locales. Only plain form labels + status strings live here — no marketing
// claims (positioning copy is still blocked, see CLAUDE.md).
export const DEMO_FORM_COPY: Record<Locale, DemoFormCopy> = {
  uz: {
    title: "Demo so'rov",
    subtitle: "Ma'lumotlaringizni qoldiring — biz siz bilan bog'lanamiz",
    fullName: "Ism familiya",
    fullNamePlaceholder: "Masalan: Aziz Karimov",
    phone: "Telefon",
    phonePlaceholder: "+998 __ ___ __ __",
    region: "Viloyat / shahar",
    regionPlaceholder: "Masalan: Toshkent sh.",
    centerName: "Avtomaktab nomi",
    centerNamePlaceholder: "Ixtiyoriy",
    studentCount: "Talabalar soni",
    note: "Izoh",
    notePlaceholder: "Savol yoki izoh (ixtiyoriy)",
    submit: "Yuborish",
    submitting: "Yuborilmoqda…",
    successTitle: "So'rov yuborildi",
    successBody: "Tez orada siz bilan bog'lanamiz.",
    errorTitle: "Xatolik",
    errorBody: "Qayta urinib ko'ring.",
    close: "Yopish",
    requiredError: "To'ldiring",
    phoneError: "Telefon raqam to'g'ri emas",
    studentCountLabels: ["50 dan kam", "50–150", "150–300", "300 dan ko'p"],
  },
  ru: {
    title: "Запрос демо",
    subtitle: "Оставьте ваши данные — мы свяжемся с вами",
    fullName: "Имя и фамилия",
    fullNamePlaceholder: "Например: Азиз Каримов",
    phone: "Телефон",
    phonePlaceholder: "+998 __ ___ __ __",
    region: "Регион / город",
    regionPlaceholder: "Например: г. Ташкент",
    centerName: "Название автошколы",
    centerNamePlaceholder: "Необязательно",
    studentCount: "Количество учеников",
    note: "Комментарий",
    notePlaceholder: "Вопрос или комментарий (необязательно)",
    submit: "Отправить",
    submitting: "Отправка…",
    successTitle: "Заявка отправлена",
    successBody: "Мы скоро свяжемся с вами.",
    errorTitle: "Ошибка",
    errorBody: "Попробуйте ещё раз.",
    close: "Закрыть",
    requiredError: "Заполните поле",
    phoneError: "Неверный номер телефона",
    studentCountLabels: ["до 50", "50–150", "150–300", "более 300"],
  },
  en: {
    title: "Request a demo",
    subtitle: "Leave your details — we'll get back to you",
    fullName: "Full name",
    fullNamePlaceholder: "e.g. Aziz Karimov",
    phone: "Phone",
    phonePlaceholder: "+998 __ ___ __ __",
    region: "Region / city",
    regionPlaceholder: "e.g. Tashkent",
    centerName: "Driving school name",
    centerNamePlaceholder: "Optional",
    studentCount: "Number of students",
    note: "Note",
    notePlaceholder: "Question or note (optional)",
    submit: "Submit",
    submitting: "Sending…",
    successTitle: "Request sent",
    successBody: "We'll get back to you shortly.",
    errorTitle: "Error",
    errorBody: "Please try again.",
    close: "Close",
    requiredError: "Required",
    phoneError: "Invalid phone number",
    studentCountLabels: ["<50", "50–150", "150–300", "300+"],
  },
};
