import type { Locale } from "@/i18n/config";
import type { DemoFormCopy } from "./DemoRequestForm";

export const DEMO_FORM_COPY: Record<Locale, DemoFormCopy> = {
  uz: {
    eyebrow: "15 daqiqa · tanishuv",
    title: "Avtomaktabingiz haqida qisqacha ayting",
    subtitle: "Uchta majburiy maydon. Keyingi qadamni sizga moslab tushuntiramiz.",
    fullName: "Ism va familiya *",
    fullNamePlaceholder: "Masalan: Aziz Karimov",
    phone: "Telefon *",
    phonePlaceholder: "+998 __ ___ __ __",
    region: "Viloyat yoki shahar *",
    regionPlaceholder: "Masalan: Samarqand",
    centerName: "Avtomaktab nomi · ixtiyoriy",
    centerNamePlaceholder: "Avtomaktab nomi",
    studentCount: "Talabalar soni · ixtiyoriy",
    submit: "Tanishuvni so‘rash",
    submitting: "Yuborilmoqda…",
    successTitle: "So‘rov qabul qilindi",
    successBody: "Ma’lumot yetib bordi. Istasangiz, suhbatni Telegram’da hozir davom ettiring.",
    telegram: "Telegram’da yozish",
    errorTitle: "So‘rov yuborilmadi.",
    errorBody: "Aloqani tekshirib, yana bir marta urinib ko‘ring.",
    close: "Oynani yopish",
    requiredError: "Bu maydonni to‘ldiring",
    phoneError: "+998 bilan to‘liq raqam kiriting",
    studentCountLabels: ["50 dan kam", "50–150", "150–300", "300 dan ko‘p"],
  },
  ru: {
    eyebrow: "15 минут · знакомство",
    title: "Коротко расскажите об автошколе",
    subtitle: "Три обязательных поля. Следующий шаг объясним с учётом вашей ситуации.",
    fullName: "Имя и фамилия *",
    fullNamePlaceholder: "Например: Азиз Каримов",
    phone: "Телефон *",
    phonePlaceholder: "+998 __ ___ __ __",
    region: "Регион или город *",
    regionPlaceholder: "Например: Самарканд",
    centerName: "Название автошколы · необязательно",
    centerNamePlaceholder: "Название автошколы",
    studentCount: "Количество учеников · необязательно",
    submit: "Запросить знакомство",
    submitting: "Отправляем…",
    successTitle: "Заявка принята",
    successBody: "Данные получены. Если хотите, продолжите разговор в Telegram прямо сейчас.",
    telegram: "Написать в Telegram",
    errorTitle: "Заявка не отправлена.",
    errorBody: "Проверьте соединение и попробуйте ещё раз.",
    close: "Закрыть окно",
    requiredError: "Заполните это поле",
    phoneError: "Введите полный номер с +998",
    studentCountLabels: ["до 50", "50–150", "150–300", "более 300"],
  },
  en: {
    eyebrow: "15 minutes · introduction",
    title: "Tell us briefly about your school",
    subtitle: "Three required fields. We will shape the next step around your situation.",
    fullName: "Full name *",
    fullNamePlaceholder: "e.g. Aziz Karimov",
    phone: "Phone *",
    phonePlaceholder: "+998 __ ___ __ __",
    region: "Region or city *",
    regionPlaceholder: "e.g. Samarkand",
    centerName: "Driving school name · optional",
    centerNamePlaceholder: "Driving school name",
    studentCount: "Number of students · optional",
    submit: "Request an introduction",
    submitting: "Sending…",
    successTitle: "Request received",
    successBody: "Your details arrived. If you prefer, continue the conversation on Telegram now.",
    telegram: "Message on Telegram",
    errorTitle: "Request was not sent.",
    errorBody: "Check your connection and try once more.",
    close: "Close dialog",
    requiredError: "Complete this field",
    phoneError: "Enter the full number with +998",
    studentCountLabels: ["Under 50", "50–150", "150–300", "Over 300"],
  },
};
